---
deploy:
  tasks:
    - export DEPLOYPATH=/home/sc2gvkn4049/public_html
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/python3 -m venv venv
    - source venv/bin/activate
    - touch __init__.py
    - /usr/local/bin/python3 -m pip install --upgrade pip
    - /usr/local/bin/python3 -m pip install --upgrade setuptools
    - /usr/local/bin/python3 -m pip install --upgrade wheel
    - /usr/local/bin/python3 -m pip install gunicorn
    - pip install -r -U requirements.txt
    - export GUNICORN_CMD_ARGS="--bind=127.0.0.1:443 --workers=16 --threads=8 --timeout=60"
    - gunicorn main:app
